import type { Metadata } from 'next'

import Header from '@/app/ui/common/Header'
import Footer from '@/app/ui/common/Footer'

import '@/app/ui/global.scss'
import { inter } from "@/app/ui/fonts";
import { cn } from '../lib/utils';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className)}>
        <Header />
        <main className="w-full">
          {children}
        </main>
        <Footer/>
      </body>
      
    </html>
  )
}
